development:
  AWS_ACCESS_KEY_ID: PLEASE_SET_AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: PLEASE_SET_AWS_SECRET_ACCESS_KEY
  AWS_BUCKET: PLEASE_SET_AWS_BUCKET

test:
  AWS_ACCESS_KEY_ID: PLEASE_SET_AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: PLEASE_SET_AWS_SECRET_ACCESS_KEY
  AWS_BUCKET: PLEASE_SET_AWS_BUCKET
