# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6e38113ca88520acca1cb7864df01f7bba7ea3af8dbda14c816fb0f3c1157ccb2459fe71178cd73b2f436c2d92e07ed2cd94c6b72c027425b8d6331b8d42d1a

test:
  secret_key_base: ba6f77556f1ea125f5b2c9eedc3ad361faa1215eed403ce36a5341d6dc5f380abe58ec2aecd4c751e572134da8ee4b459325ac518ac3a1ecff4d6f1954face49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
